{% set name = "eventgraphs" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/empiricalstateofmind/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 91753771d56481d6641957fd38db7763850b722b595f2cc4db1e33d052330fff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - networkx
    - pandas
    - numpy
    - matplotlib-base
    - scipy
    - ipython

test:
  imports:
    - {{ name|lower }}
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: https://github.com/empiricalstateofmind/eventgraphs
  summary: 'A Python library for analysing sequences of event-based data and temporal networks.'
  license: Apache-2.0 
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
